name: 'Random messages for your actions'
description: 'Grab random messages from array of strings in JSON and give them to another action.'
author: 'Johnny Benson <me@j-hnnybens-n.com>'

branding:
    icon: 'box'
    color: 'white'

inputs:
  GITHUB_TOKEN:
    description: 'Get this from secrets.GITHUB_TOKEN'
    required: true
  JSON_FILE_PATH:
    description: 'The path to the random messages'
    required: false
    default: 'random.json'

outputs:
  message:
      description: 'The message you want 2 send'

runs:
  using: 'node16'
  main: 'dist/index.js'
